baseURL = 'https://www.dragnum.ca'
languageCode = 'en-us'
title = 'DRAGNUM Dragon Boat Calgary'
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true

[params]
  custom_css = ["custom.css","special.css"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[module]
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[[module.imports]]
path = "github.com/mfg92/hugo-shortcode-gallery"

[caches]
  [caches.images]
    dir = ':cacheDir/images'